[theme]
primaryColor = "#22d3ee"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#fafafa"
font = "sans serif"
[server]
headless = true
enableCORS = false
enableXsrfProtection = false
